### ISSUE TITLE
Explore receiving incoming emails

### ISSUE THREAD

**Issue by krvajal** [sweepbright/serverless-mailparser#1]
## Summary
We aim to be able to receive emails from different property portals and store them in our systems for further processing. Each email needs to be identified and associated with a listing within SweepBright. 

## Receiving emails
For receiving emails we are going to use the [Inbound Email Parsing Webhook](https://sendgrid.com/docs/API_Reference/Parse_Webhook/inbound_email.html#-Setup) capability of SendGrid. SendGrid is already used to send emails by us. 

This works in a very simple way. First, a subdomain (ex: `ingest.sweepbright.com`) is configured with a MX record that points to the SendGrid SMTP server. This gives us a pool of email addresses on the form `[local-part]@ingest.sweepbright.com]` to which emails can be sent. Then a webhook is configured, and SendGrid will make a POST request to it every time an email is received. The request contains all the information in the email as shown in the example below.

```json
{
	"headers": "// header, not relevant",
	"dkim": "{@gmail.com : pass}",
	"content-ids": {
		"f_k112mufb0": "attachment1"
	},
	"to": "hello@ingest.dev.sweepbright.com",
	"html": "<div dir=\"ltr\"><br>hello</div>\n",
	"from": "Miguel Carvajal <krvajal.miguelangel@gmail.com>",
	"text": "hello\n",
	"sender_ip": "209.85.167.52",
	"envelope": { 
	  "to":	["hello@ingest.dev.sweepbright.com"],
	  "from": "krvajal.miguelangel@gmail.com"
	},
	"attachments": "1",
	"subject": "With Attachemnts",
	"attachment-info": {
		"attachment1": { 
	   	  "filename":"example.pdf",
	      "name":"example.pdf",
	      "type":"application/pdf",
	      "content-id":"f_k112mufb0"
	    }
	},
	"charsets": { 
		"to": "UTF-8", 
		"html": "UTF-8", 
		"subject": "UTF-8", 
		"from":"UTF-8",
		"text": "UTF-8"
	},
	"SPF": "pass",
	"attachment1": {
		"filename": "example.pdf",
		"mimetype": "application/pdf",
		"encoding": "7bit",
		"content": { 
			"type": "buffer",
			"data": "// bufer data"
		}
	}
}
``` 

This information is all we need to further process the email and extract the relevant information from it.

The webhook is gonna be a Lambda function that will be triggered throw an API Gateway event. By default, the domain is generated automatically for us, but if required it can be mapped to a custom domain. It is used only for internal consumption within Sengrid so that step shouldn't be necessary. 

### Suggested domain names
* **DEV**: ingest.dev.sweepbright.com
* **STAGING**:  ingest.staging.sweepbright.com
* **PRODUCTION**:  ingest.sweepbright.com

### Email addresses
In the first iteration, we are gonna generate an email address per channel account
in the form `[channel_type]_[channel_account_id]@ingest.sweepbright.com`.
From this info, we can determine how to parse the email (the channel type give us a clue, in combination with the sender address). Email addresses per property are not possible. 

This approach requires manual user work, as they will have to set up a forwarding system in their emails to guarantee that emails are sent to us at the provided email address.

**Comment by filipsch** [comment]
I'd go with having agents forward emails they get from portals to `<channel_account_id>@sweepbright.com`.
This is something that we at first don't show to them in the interface, but in a later step it can be a part of setting up a channel account:
- Set credentials
- Set up email forwarding
- You're good to go!

**Comment by krvajal** [comment]
Sounds good to me, I am gonna update the description accordingly.

**Comment by ohjimijimijimi** [comment]
it's a good approach! I also think using channel accounts to differentiate email is the way to go. Good analysis
