### ISSUE TITLE
Set dummy telephone number if none found

### ISSUE THREAD

**Issue by filipsch** [sweepbright/serverless-mailparser#15]
- See https://github.com/sweepbright/api/issues/5550 for context.
- Until the API is made more coherent, let's make sure the mailparser also works if potential buyers did not specify a telephone number: set it to `000` if no phone number was found from the email.

**Comment by krvajal** [comment]
Will this value pass the validation?

**Comment by filipsch** [comment]
@krvajal yes, I checked.
