### ISSUE TITLE
Remove setting default phone number

### ISSUE THREAD

**Issue by krvajal** [sweepbright/serverless-mailparser#17]
In #16 we added a default phone number when one is not found due to inconsistencies in the validation that the API does when creating a lead. This hack should be removed once the API is fixed.

**Comment by krvajal** [comment]
@filipsch do we have an issue on the API to track this?

**Comment by filipsch** [comment]
@krvajal it was linked in #15: https://github.com/sweepbright/api/issues/5550

**Comment by filipsch** [comment]
@krvajal Lead validation is made consistent on the api now, so this issue can be tackled (i.e. revert the ugly hack from yesterday): https://github.com/sweepbright/api/issues/5550
