### ISSUE TITLE
Fix problems with auto-forwarding through Gmail

### ISSUE THREAD

**Issue by filipsch** [sweepbright/serverless-mailparser#20]
FYI, there is an issue on the mailparser if you do auto-forwarding from gmail.

The email from info@immoweb.be to the admin email (e.g. immo-admin@immomalines.be) is being forwarded to immoweb@sweepbright.com, but the email is forward and the addressee of the original email is kept, instead of it being immoweb@sweepbright.com.  Because of that, the mailparsing doesn’t know which parsing it has to do, and so fails.

**Comment by krvajal** [comment]
The fix is deployed on production. We did a quick test and it works.
@filipsch you can close this once you verify that it works with CS

**Comment by filipsch** [comment]
Verified with matthias that this is working.
