### ISSUE TITLE
Mail parser for Immoweb broken since January 4th

### ISSUE THREAD

**Issue by filipsch** [sweepbright/serverless-mailparser#29]
@MatthiasVM commented on [Tue Jan 07 2020](https://github.com/sweepbright/incoming-cs-issues/issues/195)

The Immoweb mailparser is producing failed tasks since 2020-01-04T10:11:20.
I don't immediately see a difference in the lay-out of the email. 

---

@MatthiasVM commented on [Tue Jan 07 2020](https://github.com/sweepbright/incoming-cs-issues/issues/195#issuecomment-571534681)

@filipsch 

---

@filipsch commented on [Tue Jan 07 2020](https://github.com/sweepbright/incoming-cs-issues/issues/195#issuecomment-571538504)

It seems that the email structure has changed, causing the parsing to fail.

![image](https://user-images.githubusercontent.com/5768479/71890540-c7eda980-3144-11ea-94ce-4a7d5814e59e.png)

**Comment by filipsch** [comment]
I'm not sure that it's as simple as that. There are emails that arrived in the mailparser on January 4th, that were originally sent in June of 2019 (because trendimmo set up an auto-forwarding rule which retroactively sends all emails to the parser)

**Comment by MatthiasVM** [comment]
@filipsch Immovlan mailparser also started failing since 04/01

**Comment by MatthiasVM** [comment]
@filipsch Do you have an idea when this will be fixed?

**Comment by filipsch** [comment]
@MatthiasVM it's on my todo list, hopefully by EOW, otherwise before Wednesday next week.

**Comment by krvajal** [comment]
@filipsch @MatthiasVM if I remember correctly this is already fixed and running on production. Filip prepared an script to retrigger all the failed jobs since the date the bug was introduced. 
I am moving this issue to "In production". Feel free to move it back if my assumptions are incorrect

**Comment by filipsch** [comment]
Yes, indeed, I wanted to report on this issue. I also did the job to retrigger all failed jobs. There are still over 1000 emails that failed parsing, but that's because they are coming from a 'retroactive forwarding'; there are emails in there from June 2019. I'll track the work for that in another GitHub issue.
