### ISSUE TITLE
Extract lead info from Immoweb emails

### ISSUE THREAD

**Issue by krvajal** [sweepbright/serverless-mailparser#3]
Process incoming lead emails from Immoweb when a person expresses interest in a property and generate a new lead by parsing the email content and creating the lead in Sweepbright.

### QA instructions (on Production)
1) Login to the webapp as an admin
2) Go to the channels admin section and connect (or  choose an exiting) Immoweb account
3) Go to the config section of that channel account
	The URL should look something like this `https://app.sweepbright.com/channels/portals/:cannel_account_id` where `channel_account_id` is the id of the channel account. Copy that id somewhere as you are gonna need it later.
4) Go back to your properties page and choose a property. Publish that property to the Immoweb channel account for which you saved the channel account id. 
5) Once the property is published to Immoweb. Visit the property page on the Immoweb portal and express interest on it. Fill all the fields, including the name, last name, email address and add a comment.
6) After that, you should get an email from Immoweb in the mailbox of the email associated with the Sweepbright user which is the negotiator of that property.
7) Forward that email to the following email address `immoweb_:channel_account_id:@ingest.sweepbright.com`, where :channel_account_id: is the channel account id of Immoweb that you were asked to save in step 3. 

#### Expected outcome:
A lead should appear (or be updated if it already existed) within Sweepbright in the same office that the property selected on step 4 belongs to. That lead should have in the interest section the property listed in the "Active Intersts" list and when you go to interaction history a new interaction should appear with a message. The content of the message should be the same entered in the comment field on step 5.

**Comment by filipsch** [comment]
@krvajal Overall, really cool stuff, but still a couple of things:

- [ ] First and last name seem to be switched around. On Immoweb, I specify first name to be `Test`, and last name to be `Person`. This leads to the following email: 
  ![image](https://user-images.githubusercontent.com/5768479/67091718-b46a1c80-f1ad-11e9-86d9-403aad527b5d.png).
  However, in SweepBright, this person lands in the contacts as:
  ![image](https://user-images.githubusercontent.com/5768479/67091751-cb107380-f1ad-11e9-8f34-e8fd0e96dcdf.png)
- [ ] It seems that when there is an auto-appended signature included in the email forward I do, the email is not correctly parsed and the lead does not end up in SweepBright.
  ![image](https://user-images.githubusercontent.com/5768479/67091813-f7c48b00-f1ad-11e9-9ea0-467f8fde5855.png)

**Comment by krvajal** [comment]
> It seems that when there is an auto-appended signature included in the email forward I do, the email is not correctly parsed and the lead does not end up in SweepBright.

Can you provide me with the channel account id of that Immoweb channel?

**Comment by filipsch** [comment]
@krvajal all my test emails were sent to `immoweb_770d1483-3e6b-43da-a13a-9a87baf72299@ingest.sweepbright.com`, the immoweb channel account for filip@sweepbright.com on production.

**Comment by krvajal** [comment]
@filipsch the first issue, the one related to the name, has been solved.

**Comment by xavez** [comment]
Well holy crap. This is incredibly awesome.
